---
- hosts: localhost
  become: true
  become_user: root
  vars:
   ansible_become_pass: ansible

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using war file
    command: docker build -t myproject .
    args:
      chdir: /home/ansible

  - name: create tag to image
    command: docker tag myprojec johnte/myproject:$BUILD_NUMBER

  - name: loginto docker
    command: docker login --username johnte --password King5555!

  - name: push image on to dockerhub
    command: docker push johnte/myproject:$BUILD_NUMBER
    
  - name: Do deployment in Docker Swarm cluster
    command: docker service create --name mysvc-ansible --replicas 1 -p 8282:8080 johnte/myproject:$BUILD_NUMBER
    
  - name: remove docker images form ansible server
    command: docker rmi --force myproject:CICD johnte/myproject:$BUILD_NUMBER
    ignore_errors: yes
    
#  - name: Do deployment to kuberetes Prod
 #   command: kubectl apply -f https://raw.githubusercontent.com/devops-learner01012022/DevOps_ClassNotes/master/CICD%20pipeline/kubedeployment.yml
